# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: def51c1a19ed5fb006404efda541b59b089e4e012f8178e976c29ae623b8947fda98ec4010b9a8742e2cd37af39f64009d1b4b22a82a6d188e5ebbf93769f8f1

test:
  secret_key_base: 4344493648363f97a8bc6edd6da3204af34f0d4faa0ca8c92fbdfcfdf8c598c38de87f3516d7c38a74d1e147eca74a813a15621ec8432b3630b854d107b163fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
